SELECT USER
FROM DUAL;
--==> SCOTT 

--○ 테이블 생성
CREATE TABLE TBL_MEMBERLIST
( ID    VARCHAR2(30)
, PW    VARCHAR2(20)    NOT NULL
, NAME  VARCHAR2(50)    NOT NULL
, TEL   VARCHAR2(50)    NOT NULL
, EMAIL VARCHAR2(100)
, CONSTRAINT MEMBERLIST_ID_PK PRIMARY KEY(ID)
, CONSTRAINT MEMBERLIST_TEL_UK UNIQUE(TEL)
);
--==>> Table TBL_MEMBERLIST이(가) 생성되었습니다.

--○ 데이터 INSERT 
INSERT INTO TBL_MEMBERLIST VALUES ('RAINBOW', '123456', '권홍비', '010-1111-1111', 'rainbow@test.co.kr');
--> 한줄 구성
INSERT INTO TBL_MEMBERLIST VALUES (?, ?, ?, ?, ?)
;

--○ 데이터 SELECT 
SELECT ID, NAME, TEL, EMAIL
FROM TBL_MEMBERLIST;
--> 한줄 구성
SELECT ID, NAME, TEL, EMAIL FROM TBL_MEMBERLIST
;

ROLLBACK;
commit;